#!/bin/bash

# Functions to change the color of text printed the terminal

function col_black {
    echo -e "\033[0;30m$@\033[0m"
    }
function col_red {
    echo -e "\033[0;31m$@\033[0m"
    }
function col_green {
    echo -e "\033[0;32m$@\033[0m"
    }
function col_brown {
    echo -e "\033[0;33m$@\033[0m"
    }
function col_blue {
    echo -e "\033[0;34m$@\033[0m"
    }
function col_purple {
    echo -e "\033[0;35m$@\033[0m"
    }
function col_cyan {
    echo -e "\033[0;36m$@\033[0m"
    }
function col_lgray {
    echo -e "\033[0;37m$@\033[0m"
    }

#light versions
function col_dgray {
    echo -e "\033[1;30m$@\033[0m"
    }
function col_lred {
    echo -e "\033[1;31m$@\033[0m"
    }
function col_lgreen {
    echo -e "\033[1;32m$@\033[0m"
    }
function col_yellow {
    echo -e "\033[1;33m$@\033[0m"
    }
function col_lblue {
    echo -e "\033[1;34m$@\033[0m"
    }
function col_lpurple {
    echo -e "\033[1;35m$@\033[0m"
    }
function col_lcyan {
    echo -e "\033[1;36m$@\033[0m"
    }
function col_white {
    echo -e "\033[1;37m$@\033[0m"
    }

# echo -e "`col_black  black`         `col_dgray   dark gray`"
# echo -e "`col_red    red`           `col_lred    light red`"
# echo -e "`col_green  green`         `col_lgreen  light green`"
# echo -e "`col_brown  brown`         `col_yellow  yellow`"
# echo -e "`col_blue   blue`          `col_lblue   light blue`"
# echo -e "`col_purple purple`        `col_lpurple light purple`"
# echo -e "`col_cyan   cyan`          `col_lcyan   light cyan`"
# echo -e "`col_lgray  light gray`    `col_white   white`"
