#!/bin/bash

# for pushing to all of my repositores at github (would need to modify as new repositories are added)

DIR=`pwd`
LOCAL_REPO=(
    ~/files/python
    ~/files/data
    ~/files/julia
    ~/files/C
    ~/files/go-game
    ~/files/repos/binaries
    ~/files/repos/homework
    ~/files/repos/latex
    ~/files/repos/lilypond
    ~/files/repos/mwBASE
    ~/files/repos/mwEVT
    ~/files/repos/r-sandbox
    ~/files/repos/ubuntu-config
    )

for repository in ${LOCAL_REPO[@]}
do
    cd $repository
    echo Pushing to $repository
    gitall
    echo ""
done

cd $DIR
