#!/bin/bash

# for pushing to all of my repositores at github (would need to modify as new repositories are added)

DIR=`pwd`
LOCAL_REPO=(
    ~/bin
    ~/files/python
    ~/files/R
    ~/files/ubuntu-config
    ~/files/data
    ~/files/julia
    ~/files/C
    ~/files/homework
    ~/files/latex
    ~/files/github_website
    )

for repository in ${LOCAL_REPO[@]}
do
    cd $repository
    echo Pushing to $repository
    gitall
    echo ""
done

cd $DIR
