#!/bin/bash

# for pushing to all of my repositores at github (would need to modify as new repositories are added)

DIR=.

cd ~/bin
echo Pushing to ~/bin
gitall
echo ""

cd ~/files/python
echo Pushing to ~/files/python
gitall
echo ""

cd ~/files/R
echo Pushing to ~/files/R
gitall
echo ""

cd ~/files/ubuntu-config
echo Pushing to ~/files/ubuntu-config
gitall
echo ""

cd ~/files/data
echo Pushing to ~/files/data
gitall
echo ""

cd ~/files/julia
echo Pushing to ~/files/julia
gitall
echo ""

cd $DIR
