#!/bin/bash

### start fresh
rm -f output_latex.pdf    # don't name anything output_latex.pdf

# compile the .tex once
pdflatex -interaction=nonstopmode main.tex

# if refs.bib is in the directory, then run additional code
# (to get the references right
if [ -e ./refs.bib ]; then
    bibtex main.aux
    pdflatex -interaction=nonstopmode main.tex 
    pdflatex -interaction=nonstopmode main.tex 
fi

# clean up
rm -f main.aux main.log main.nav main.snm
rm -f main.toc main.out main.blg main.bbl

# rename and open
mv main.pdf output_latex.pdf

if [ "$1" == "--noprint" ]; then
    echo "no print option"
else
    evince output_latex.pdf
fi
