#!/bin/bash

### TODO: do a check to see if main.tex is in the working directory,
###       if so, then compile that file, otherwise compile the first
###       argument. if only one .tex file exists in the directory,
###       compile that file without expecting an argument

### start fresh
rm -f output_latex.pdf    # don't name anything output_latex.pdf

# compile the .tex once
pdflatex -interaction=nonstopmode main.tex

# if refs.bib is in the directory, then run additional code
if [ -e ./refs.bib ]; then
    bibtex main.aux
    pdflatex -interaction=nonstopmode main.tex 
fi

# get the references correct (for both regular latex references and natbib)
pdflatex -interaction=nonstopmode main.tex 
pdflatex -interaction=nonstopmode main.tex 

# clean up
rm -f main.aux main.log main.nav main.snm
rm -f main.toc main.out main.blg main.bbl
rm -f texput.log

# rename and open
mv main.pdf output_latex.pdf

# default is to evince the out file, unless the
# command is texbuild --noevince
if [ "$1" == "--noevince" ]; then
    echo "no evince option"
else
    evince output_latex.pdf
fi
